# Generated by Django 5.2.1 on 2025-06-02 16:18

import django.contrib.auth.models
import patrimonials.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('bjects', patrimonials.models.UsuarioManager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
